export const CALCULATE_COMMISSION = "CALCULATE_COMMISSION";
export const CLOSE_MODAL_WITH_PHONE = "CLOSE_MODAL_WITH_PHONE";
export const OPEN_MODAL_WITH_PHONE = "OPEN_MODAL_WITH_PHONE";
export const CLOSE_MODAL_WITH_ADDRESS = "CLOSE_MODAL_WITH_ADDRESS";
export const OPEN_MODAL_WITH_ADDRESS = "OPEN_MODAL_WITH_ADDRESS";
export const OPEN_DATA_AGREEMENT = "OPEN_DATA_AGREEMENT";
export const CLOSE_DATA_AGREEMENT = "CLOSE_DATA_AGREEMENT";

export const SEND_FORMDATA_EMAIL_START = "SEND_FORMDATA_EMAIL_START";
export const SEND_FORMDATA_EMAIL_SUCCESS = "SEND_FORMDATA_EMAIL_SUCCESS";
export const SEND_FORMDATA_EMAIL_FAIL = "SEND_FORMDATA_EMAIL_FAIL";